### ISSUE TITLE
Difference between VelocityComponent and VelocityTransitionGroup?

### ISSUE THREAD

**Issue by jeffijoe** [twitter-fabric/velocity-react#103]
When should we use one vs the other? A clarification in the readme would be gravy!

**Comment by finneganh** [comment]
Use `VelocityTransitionGroup` when you want the behavior of a React `TransitionGroup` (animations on elements entering / leaving the DOM). Docs here: https://facebook.github.io/react/docs/animation.html

Use `VelocityComponent` otherwise.

**Comment by jeffijoe** [comment]
I guess my question is, for a new animation, why would I *want* to chose one over the other?

**Comment by finneganh** [comment]
It comes down to if you're animating an element in place, vs. if you need
to animate a component as it enters or leaves the DOM. If you check the
demos, the three on the left are `VelocityComponent` whereas the two on the
right are `VelocityTransitionGroup`.

**Comment by jeffijoe** [comment]
Ah, okay, thanks! Basically right now I am using CSS transition groups because the keyframes are easy to work with in CSS. What would be the best path for me to come close to that experience with Velocity?

**Comment by finneganh** [comment]
If you're having the CSS animations just on elements so that they animate
when they appear in the DOM, then probably VelocityTransitionGroup will
match the behavior you expect. If you've been dynamically adding
animation-specific classes to elements based on some triggering event, then
use VelocityComponent.

You can do multi-step animations in Velocity, which you might be used to
with keyframes, by using `registerEffect` and specifying a series of
`calls`. (This is for cases where straightforward tweening between two
values is not enough.) Look at Velocity's documentation for
`RegisterEffect`, though `velocity-react` also has a helper for it that
prevents naming collisions.
