### ISSUE TITLE
Cannot Reverse Animations

### ISSUE THREAD

**Issue by matthax** [twitter-fabric/velocity-react#115]
The reverse call for animations does not seem to function properly, or the method of calling is not clear. I have tried setting reverse as a property on a ```VelocityTransitionGroup``` and as a property in ```enter``` and in ```leave``` but ```reverse``` never seems to get called.

Am I doing it incorrectly or is the functionality for reverse not available?

**Comment by finneganh** [comment]
The `"reverse"` value for an animation is not a great fit for `VelocityTransitionGroup` because elements may need to animate out without having been animated in. (See: http://velocityjs.org/#reverse Reverse just undoes the most recent animation on an element)

It's best to make an opposite animation.
