### ISSUE TITLE
Simple highlight-then-fade example?

### ISSUE THREAD

**Issue by dlong500** [twitter-fabric/velocity-react#116]
Maybe I'm just missing something, but I'm not clear how to do just a basic highlight-then-fade when a prop changes.

In other words, say I have a div with a number in it, and when the "changed" prop is true I want to fade in the background color from transparent to orange.  Then after 2 seconds I want the background color to fade back to transparent.

I can get things working to toggle between the two background colors based on the value of the "changed" prop, but that's not what I want to do.  I want to fade in and then out when the "changed" prop is true and not do any animation when the "changed" prop is reset to false.

Am I being clear?

**Comment by finneganh** [comment]
Since you want your animation to be affected by the derivative of your state, rather than the state itself, I'd recommend calling the `runAnimation` method on a `VelocityComponent` in your `componentDidUpdate` method on detecting that the current value is different from the previous value (which are passed to `componentDidUpdate`).
