### ISSUE TITLE
Requiring UI Pack with Webpack

### ISSUE THREAD

**Issue by travisbloom** [twitter-fabric/velocity-react#18]
Is there any specific reason the Velocity UI pack isn't required by default? What is best practice for adding this to a webpack project? Importing it globally doesn't help as the package pulls directly from 'velocity-animate', not the global Velocity object I create within my project.

Currently I'm aliasing 'velocity-animate' to a internal module and adding the UI pack manually but this seems messy.

Thanks, this project looks awesome.

**Comment by Mtpc** [comment]
I noticed that too, the `velocity-animate` package pulled by velocity-react's components is different from the one you would normally include globally in your project, since it comes bundled as its own dependency, effectively causing the UI pack to register on an object different that the one used by `velocity-react`.
My current workaround is to require globally the correct `velocity-animate` module
```javascript
require('velocity-react/node_modules/velocity-animate')
require('velocity-react/node_modules/velocity-animate/velocity.ui')
```

**Comment by phopkins** [comment]
Is this a case where you have Velocity already as a dependency in your project? In that case, does `npm dedupe` do what you need to collapse the dependency tree?

**Comment by phopkins** [comment]
FWIW the demo app uses webpack, though it's obviously quite toy. We have this at the top of the top-level component:

```
require('velocity-animate');
require('velocity-animate/velocity.ui');
```

**Comment by travisbloom** [comment]
But will https://github.com/twitter-fabric/velocity-react/blob/master/velocity-component.js#L42 use the version with UI pack added here: https://github.com/twitter-fabric/velocity-react/blob/master/demo/main.jsx#L6?

At least in my testing, it will pull the Velocity global object directly from the npm_modules folder. Again, there may be a webpack config I'm unaware of that fixes this

**Comment by phopkins** [comment]
Hrm. I noticed that the demo isn't the best case because it doesn't NPM-in the `velocity-react` bits.

Regardless, in a separate toy project I still couldn't repro. I see that in `./node_modules/velocity-react/node_modules` that there's no `velocity-animate` package of its own. NPM didn't install one there, and it's instead letting the one in `./node_modules/velocity-animate` be used.

This is with NPM 2.14.4.

My package.json is:

```
{
  "name": "velocity-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "react": "^0.13.3",
    "velocity-animate": "^1.2.3",
    "velocity-react": "^1.0.0"
  },
  "devDependencies": {
    "babel-core": "^5.8.25",
    "babel-loader": "^5.3.2",
    "react-hot-loader": "^1.3.0",
    "style-loader": "^0.12.4",
    "webpack": "^1.12.2",
    "webpack-dev-server": "^1.12.0"
  }
}
```

And do the `require` for `velocity-animate` and `velocity-animate/velocity.ui` in an app.js, followed by a `require` for the `MainComponent` that `require`s `velocity-react/velocity-component`.

**Comment by phopkins** [comment]
Here's the gist of my packaging test: https://gist.github.com/phopkins/d127287ffa950d3b0d2c

**Comment by larryhengl** [comment]
Nice.  This appears to have solved my First Argument error. Similar to https://github.com/julianshapiro/velocity/issues/327

**Comment by phopkins** [comment]
Closing, since I think `npm dedupe` pretty much solves this. Please re-open with more info if that's not the case.
