### ISSUE TITLE
Pausing VelocityTransitionGroup enter / leave animation

### ISSUE THREAD

**Issue by skiptomyliu** [twitter-fabric/velocity-react#211]
Hello!  I'm a bit new to the library, but am enjoying it a lot thus far. 

Is it possible to "pause" an animation during the leave or enter animation phase when using VelocityTransitionGroup?  I was working through `examples/scrolling-group.jsx` demo that was included and was attempting to figure out how to pause the animation.  Any insight or direction would be appreciated on how to approach this.

**Comment by finneganh** [comment]
What effect are you trying to achieve?

**Comment by skiptomyliu** [comment]
I have an automatic scrolling slide show of images.  It's currently modeled after the demo scrolling-group.jsx because the behavior is nearly identical with some minor tweaks.  

However, I would like the end user to be able to pause / play the slide show.  I can "pause" the adding of additional items once the animation finishes entering/leaving, but actually pausing during the animation is proving a challenge.

**Comment by finneganh** [comment]
That would be tricky. Calling `Velocity.stop` on the animated elements would stop them from animating. But, it would also cause the `TransitionGroup` to keep them around because `stop` keeps the `complete` callback from firing, which is how `VelocityTransitionGroup` can tell `TransitionGroup` to finally remove the element.

You might have better luck wrapping each image in a `<VelocityComponent>`, which can have its animation stopped (by setting its `animation` prop to `null`).
