### ISSUE TITLE
Online Demo please?

### ISSUE THREAD

**Issue by winkler1** [twitter-fabric/velocity-react#25]
Looks interesting -- would an online demo be possible? Would like to add to react.rocks, thanks

**Comment by phopkins** [comment]
Good idea. I'll look into this.

**Comment by jmfurlott** [comment]
@phopkins I would be happy to get this running on github pages for the repo if you want me to

**Comment by phopkins** [comment]
That would be super awesome. Shouldn't be tooo much of a thing to export
the demo bundle in some fashion. But I suppose there's always wrinkles.

**Comment by jmfurlott** [comment]
Nah. Will check it out after work!

**Comment by julianshapiro** [comment]
I will link the demo from the velocity docs too.

**Comment by jmfurlott** [comment]
Sorry for the delay @phopkins but I just got it up running on my fork on the `gh-pages` branch.  I added a build task which the same as the demo script but it uses `webpack` instead of the dev server.  Additionally, I broke out the `demo/index.html` and put it in the root with updated paths.

I had to remove `build` from the `.gitignore` so that the files would be available as well in version control.  Obviously this branch should never be merged into `master`. 

It is visible here http://jmfurlott.github.io/velocity-react/

@phopkins if you want me to merge this in, I think I need you to create a `gh-pages` so I have a branch that I can make a PR on

**Comment by phopkins** [comment]
Shiny! Made the `gh-pages` branch.

Ideally, I think we should check any code / location changes in to master
(i.e. make the demo index.html work from wherever) and then just have
gh-pages for the pre-built `build` directory.

Did you run into anything where the webpack-dev-server doesn't like
referencing the `bundle.js` file from `build`? I'd like to figure out how
to sort that out if it's possible. I can look at it if it's out-of-scope
for you. (This came up in another bug, where webpacking and just opening
the `index.html` file didn't work, but running through the dev server did.)

**Comment by jmfurlott** [comment]
Ugh so weird. I couldn't make the PR because it said our commit history was completely different.  I ended up having to re-fork and re-add the changes. 

I think we have to have a `index.html` in the root for `gh-pages`. There may be a better way to do this.

I am not sure what you mean by the webpack-dev-sever and referencing the build? I didn't touch the dev sever as I don't want it running at all.  If you can point me to more info (via another issue), I can check it out

**Comment by phopkins** [comment]
Here's the PR that was put in regarding `build/bundle.js` vs. `bundle.js`: https://github.com/twitter-fabric/velocity-react/pull/16

I'm ok with index.html in the root for the demo. Could just `.npmignore` it out.

**Comment by jmfurlott** [comment]
In the `gh-pages` you don't need to start a server in order to view the `index.html`. Making that possible is essentially all my PR is.  You have to run `npm run build`, which executes and just spits out `build/bundle.js` (but this path could be anything), and then the `index.html` just loads in that bundle.  Obviously nothing is watching the changes or anything, but it works completely statically

**Comment by phopkins** [comment]
Cool. Thank for sorting this out. I'll merge the PR to the `gh-pages`
branch, which will get the demo up there, and then I can look into the
paths and keeping the static version consistent with the demo going forward.

**Comment by phopkins** [comment]
Thanks to @jmfurlott, the basic demo is accessible at: http://twitter-fabric.github.io/velocity-react/

**Comment by winkler1** [comment]
![](http://4.bp.blogspot.com/-Q5tVyMkoE_0/UUw8v4cgbAI/AAAAAAAAA4s/5DwyopBdidc/s400/pulp_thumb+christian+d.jpg)
