### ISSUE TITLE
VelocityTransitionGroup positioning on first tick

### ISSUE THREAD

**Issue by arush** [twitter-fabric/velocity-react#38]
As per the readme, I'm using the style key in the enter/leave animation hash to set absolute positioning for the child elements to not affect the container height, but the absolute positioning stays on the elements even after the enter/leave animations are complete.

I expected it to default back to its original positioning once velocity-react is done animating. Since it doesn't do this, the parent container loses height/width.

**Comment by phopkins** [comment]
The "style" just gets applied, since it’s done via Velocity / DOM rather than React it's not straightforward to just "undo". You can often override it in the animation if that's necessary.

For doing a crossfade-like effect, I'd recommend only using “position: absolute” for the leaving element, leaving the parent to size naturally from any entering element.
