### ISSUE TITLE
Any way to turn off animation on demand ?

### ISSUE THREAD

**Issue by richard-lopes** [twitter-fabric/velocity-react#56]
Hi,

I have an use case here where we use a `VelocityTransitionGroup` to animate rows entering and leaving a table. And that works great.
However we are trying to turn off the animation when filtering is applied to the table.
Is there any way we can control if animation enter/leave is happening or not ?

Thanks,

**Comment by phopkins** [comment]
There may be some hacks you could do by temporarily changing the `enter` / `leave` props when you know filtering is happening. You could also try some nested shenanigans (in other words, make filtering change rows' display or inner contents rather than adding / removing them from the parent element).

**Comment by richard-lopes** [comment]
I see. Ok I am going to see if I can alter `enter` / `leave` on demand. Thanks.

**Comment by richard-lopes** [comment]
For the sake of sharing I have it to work.
I ended up with something that looks like this:
```Javascript
  render() {
    const props = this.props.enable ? {enter: fadeInRight, leave: fadeOutRight} : {};

    return (
      <VelocityTransitionGroup component="tbody" {...props}>
        {this.props.children}
      </VelocityTransitionGroup>
    );
  }
```
