### ISSUE TITLE
setting `display: none` on first tick can cause issues for children

### ISSUE THREAD

**Issue by chrisdrackett** [twitter-fabric/velocity-react#61]
Setting `display: none` here:

https://github.com/twitter-fabric/velocity-react/blob/master/velocity-transition-group.js#L153

has the potential to cause issues with any components that happen to be under a `VelocityTransitionGroup` that run style based code as part of `ComponentDidMount`. For example we have list items that check their width and size the text inside accordingly. If these list items are a child of a parent that uses `VelocityTransitionGroup` to animate in they will come in at their minimum size as they are getting a width of `0`. Then the next time they render they will size themselves correctly.

**Comment by phopkins** [comment]
That line is in there because, due to React's TransitionGroup's API, we
have no way of getting all of the children that are entering or leaving
other than collecting them and waiting a tick to know that the collection
is complete. We want to batch all of the child animations in one go in
order to support Velocity options like stagger.

Without that display: none or an alternate means of hiding, elements would
flash in for that tick before the animation started.

I could imagine a position: absolute / opacity: 0 combo, or height: 0, or
something else that would keep the element from appearing. Would one of
those work for your use case? Do you have ideas about a good means of
parameterization?

**Comment by chrisdrackett** [comment]
for my current use case anything that hides the element while keeping its physical measurements the same would be ideal. So I think either `absolute/opacity` and `visibility: hidden` should both provide that.

**Comment by phopkins** [comment]
Looking at a fix in #62

**Comment by phopkins** [comment]
Live in 1.1.2.
