### ISSUE TITLE
Leave animation not triggering in VelocityTransitionGroup

### ISSUE THREAD

**Issue by samuraisam** [twitter-fabric/velocity-react#79]
Using VelocityTransitionGroup, I am having an issue getting the leave animation to play, and have gotten into the weeds with both react-router and with velocity-react, but can not figure out the origin of the problem. 

Here is the sample site: http://bird-683.getforge.io/#/setup/index?_k=9wdmqy 

If you click through the demo (the demo is of a mobile app) - you will notice that the `leave` animations do not play. If you pull up the console, you'll also notice that I've added logging for both the leave and enter events in the `VelocityTransitionGroupChild` - both of which appear to fire correctly. This is what leads me to believe I may be encountering odd behavior in velocity-react itself, since the events appear to be firing correctly from the original ReactTransitionGroup.

I'm using VelocityTransitionGroup in the following way:

```js
class Setup extends React.Component {
  static get contextTypes() {
    return {router: React.PropTypes.object.isRequired}
  }

  componentDidMount() {
    this.context.router.push('/setup/index');
  }

  render() {
    const { pathname } = this.props.location;
    console.log("pathname =", pathname);

    return (
      <div className="setup">
        <div className="intro-logo" />
        <VelocityTransitionGroup
          component="div"
          enter={{animation: "transition.slideRightBigIn"}}
          leave={{animation: "transition.slideLeftBigOut"}}>
          {React.cloneElement(this.props.children || <div/>, {key: pathname})}
        </VelocityTransitionGroup>
      </div>
    )
  }
}
```

I am using the most recent versions of react, velocity-react, and react-router.

**Comment by phopkins** [comment]
For things like this, turning the animation speed waaaaay down is a good way to test this. That will let you inspect the DOM as it's moving.

My guess on this is that the animation is playing, but since you have 2 elements in the container, one is either covering the other or, more likely, bumping it down so that it can't be seen.

You may want to look over the sample code for the crossfade animation, which shows switching a leaving element over to position: absolute so that both elements can coexist on screen.
