### ISSUE TITLE
minor-versioning issue?

### ISSUE THREAD

**Issue by liorbrauer** [twitter-fabric/velocity-react#94]
Hi,

First, thanks for updating velocity-react to support React 15. 

I wanted to inform that on my project, we had a dependency for:
```json
"velocity-react": "^1.1.1"
```
In our `package.json`, while still using React 0.14.xx. The minor version update for this package caused 2 version of react to be loaded when deployed in production (0.14 and 15), which of course broke the build. 

Maybe it will be wiser to give it a bigger version bump, since depending solely on React 15 now is a big change (or, alternatively, depending on react 0.14 and 15, I've seen other packages doing this)?

Thanks

**Comment by finneganh** [comment]
Sorry to hear you had an issue. The 1.1.5 change does just add React 15 as an option along with 0.14 (the velocity-react code was already compatible with both) but NPM's interpretation of that seems to have done you wrong.

I suspect what happened was you're using a version of NPM that is installing peerDependencies automatically, and NPM pulled in React 15 off of velocity-addons-transition-group's peerDependencies (which it got by choosing to use v15 of that package, rather than 0.14, even though both are supported).

You way want to depend specifically on velocity-addons-transition-group at 0.14.x. velocity-react supports both.

I'm sorry this caused a production problem. Have you looked into npm shrinkwrap to try to keep deployed versions more nailed down?

**Comment by liorbrauer** [comment]
@finneganh Thanks for the reply. I assumed without looking that the version bump on your part explicitly depended on React 15, but I see you're correct. I'll look into shrinkwrap and perhaps a newer version of NPM that doesn't automatically install peerDependencies.

Again, thanks for your help and contribution!

**Comment by finneganh** [comment]
Good luck! Thanks for using velocity-react!
